# Generated by Django 3.2.6 on 2021-12-06 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_entradadiario_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradadiario',
            name='descripcion',
            field=models.CharField(blank=True, default='', max_length=220),
        ),
    ]
